dist: trusty
language: node_js
node_js:
  - 'lts/*'
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: pretest
      name: Pretest
      before_script: skip
      script:
        - commitlint-travis
        - yarn lint
      after_failure: skip
    - stage: test
      name: Chrome
      env:
        - SELENIUM_BROWSER=chrome
        - BROWSER_PATH=/usr/bin/google-chrome-stable
        - SCREENSHOT_DIR=travis-screenshots
      addons:
        chrome: stable
    - stage: test
      name: Firefox
      env:
        - SELENIUM_BROWSER=firefox
        - BROWSER_PATH=firefox
        - SCREENSHOT_DIR=travis-screenshots
      addons:
        firefox: latest
    - stage: test
      name: Safari
      os: osx
      env:
        - SELENIUM_BROWSER=safari
        - SCREENSHOT_DIR=travis-screenshots
      before_install: sudo /usr/bin/safaridriver --enable
    - stage: deploy
      if: branch = master && type != pull_request
      before_script: skip
      script: yarn build
      after_failure: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: bash deploy.sh
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH
  # Codecs needed for Firefox to play audio.
  - |
    if [[ "$SELENIUM_BROWSER" == "firefox" ]]; then
      sudo apt-get install -y -qq ubuntu-restricted-addons;
    fi
before_script:
  # Build budle.js
  - yarn build
  # Increase the shared memory mountpoint. Chrome or something in the tests is
  # taking up more shared memory than is available which causes tests to fail.
  # See https://github.com/SeleniumHQ/docker-selenium/issues/431
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo mount -o remount,size=64G /run/shm
    fi
script:
  - |
    if [[ $HEADLESS -eq 0 && "$TRAVIS_OS_NAME" == "linux" ]]; then
      xvfb-run --server-args="-screen 0 1920x1080x16" yarn mocha --bail
    else
      yarn mocha --bail
    fi
# When the test script fails, push screen shots to a git branch.
after_failure: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR/travis-screenshots"
    git init
    git checkout -b travis-screenshots
    git add .
    git -c user.name="$GITHUB_USER" -c user.email='travis' commit -m 'Travis CI screenshots'
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG travis-screenshots 2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
